baseURL = "/"
languageCode = "en-us"
title = "Census Linking Project"
theme = "base-hugo-theme"
googleAnalytics = ""
paginate = 5
enableRobotsTXT = true

[imaging]
resampleFilter = "box"
quality = 70
anchor = "smart"

[markup.goldmark.renderer]
unsafe = true

[params]
  # google_analytics_id=""
  hideFooter=false
  includeBootstrapJs=true
  containerMaxWidth=1200
  showActiveNav=true


# main menu
[menu]  
    [[menu.main]]
        Name = "Home"
        url = "/"
        weight = 1

    [[menu.main]]
        name = "About"
        url = "/about"
        weight = 2

    [[menu.main]]
        name = "Data"
        url = "/data"
        weight = 3    

    [[menu.main]]
        name = "Methods"
        url = "/methods"
        weight = 4

    [[menu.main]]
        name = "Who We Are"
        url = "/who-we-are"
        weight = 5

    [[menu.main]]
        name = "Contact"
        url = "/contact"
        weight = 6    

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"


