backend:
  name: git-gateway
  branch: carousel # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "content/uploads" # Media files will be stored in the repo under content/uploads (to make the image processing work we have to use this technique to spoof the images being page resources
public_folder: "/uploads" # The src attribute for uploaded media will begin with this

collections:
  #HOMEPAGE
  - label: "Home"
    name: home
    preview_path: /
    files:
        - label: Homepage Content
          name: homepage_content
          file: "data/home.yaml"
          extension: "yaml"
          fields:
            - {label: Page Title, name: title, widget: string}
            - {label: Description, name: description, required: false, hint: for search engines and social media, widget: string}
            - {label: Hero panel text, name: herotext, widget: string}
            - {label: Get the Data prompt, name: dataprompt, widget: string}
            - {label: Prompt subheading, name: dataprompt2, widget: string}
            - {label: Video prompt, name: videoprompt, widget: string}
            - {label: Prompt subheading, name: videoprompt2, widget: string}

  #About
  - label: "About Page"
    name: about
    preview_path: /about
    files:
      - label: About Page Content
        name: aboutpage_content
        file: "content/about/_index.md"
        fields:
          - {label: Page Title, name: title, widget: string}
          - {label: Description, required: false, name: description, hint: for search engines and social media, widget: string}
          - {label: Blockquote, required: false, name: aboutblock, widget: string}
          - {label: Image, required: false, name: image, widget: image}
          - {label: Body text, required: false, name: body, widget: markdown}
  
  #Data
  - label: "Data Page"
    name: data
    preview_path: /data
    files:
      - label: Data Page Content
        name: datapage_content
        file: "content/data/_index.md"
        fields:
          - {label: Page Title, name: title, widget: string}
          - {label: Description, required: false, name: description, hint: for search engines and social media, widget: string}
          - {label: Introduction, required: false, name: intro, widget: markdown}
          - {label: Column 1, required: false, name: para1, widget: markdown}  
          - {label: Column 2, required: false, name: para3, widget: markdown} 

  #Video
  - label: "Video Page"
    name: video
    preview_path: /video
    files:
      - label: Video Page Content
        name: videopage_content
        file: "content/video/_index.md"
        fields:
          - label: Video Section
            name: videoSection
            widget: object
            fields:
              - {label: Title, name: title, widget: hidden}
              - {label: Carousel Heading, name: heading, widget: string}
              - {label: Carousel Subheading, name: para, widget: string}
              - label: Videos
                name: videos
                widget: list
                fields:
                  - {label: Unique ID, name: uid, widget: string}
                  - {label: Youtube video ID, name: videoId, widget: string}
                  - {label: Video title, name: title, widget: string}
    
  #Methods
  - label: "Methods Page"
    name: methods
    preview_path: /methods
    files:
      - label: Methods Page Content
        name: methodspage_content
        file: "content/methods/_index.md"
        fields:
          - {label: Title, name: title, widget: hidden}
          - {label: Page Title, name: displaytitle, widget: string}
          - {label: Description, required: false, name: description, hint: for search engines and social media, widget: string}
          - {label: Blockquote, required: false,name: blockquote, widget: string}
          - {label: Body Text, required: false, name: body, widget: markdown}  
         
  
  #TEAM
  - label: "Our Team"
    name: team_members
    preview_path: /team
    files:
      - label: Our Team Text
        file: "content/team/_index.md"
        name: ourteamtext
        fields:
          - {label: Title, name: title, widget: hidden}
          - {label: Page Title, name: displaytitle, widget: string}
          - {label: Description, required: false, name: description, hint: for search engines and social media, widget: string}
          - {label: Introduction, required: false, name: intro, widget: markdown} 
      - label: Our Team Members 
        file: "data/people/people.yaml"
        name: people
        fields:
          - label: Team Member
            name: team
            widget: list
            fields:
              - {label: Team Member Name, name: name, widget: string}
              - {label: Team Member Link, required: false, name: link, widget: string}
              - {label: Organization, name: org, required: false, widget: string} 
          
  #Contact
  - label: "Contact Page"
    name: contact
    preview_path: /contact
    files:
      - label: Contact Page Content
        name: contactpage_content
        file: "content/contact/_index.md"
        fields:
          - {label: Page Title, name: title, widget: string}
          - {label: Description, required: false, name: description, hint: for search engines and social media, widget: string}
          - {label: Body Text, required: false, name: body, widget: markdown}           
            
  

  - label: Social Media Metadata
    name: social-media
    files: 
      - label: Social media image and description
        file: "data/social.yaml"
        preview_path: /
        extension: "yaml"
        create: false
        name: socialitems
        fields:
          - {label: "Social media description", required: false, name: "social_description", widget: string}
          - {label: Social media image, required: false, name: social_image, widget: image, hint: 'Optimum resolution is 1200x675 pixels'}
          