backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "content/uploads" # Media files will be stored in the repo under content/uploads (to make the image processing work we have to use this technique to spoof the images being page resources
public_folder: "/uploads" # The src attribute for uploaded media will begin with this

collections:
  #HOMEPAGE
  - label: "Home"
    name: home
    preview_path: /
    files:
        - label: Homepage Content
          name: homepage_content
          file: "data/home.yaml"
          extension: "yaml"
          fields:
            - {label: Hero panel text, name: herotext, widget: string}
            - {label: Get the Data prompt, name: dataprompt, widget: string}
            - {label: Prompt subheading, name: dataprompt2, widget: string}
  
  #TEAM
  - label: "Our Team"
    name: team_members
    preview_path: /team
    files:
      - label: Our Team Members 
        file: "data/people/people.yaml"
        name: people
        fields:
          - label: Team Member
            name: team
            widget: list
            fields:
              - {label: Team Member Name, name: name, widget: string}
              - {label: Organization, name: org, required: false, widget: string} 
          
           
            
  

  - label: Social Media Metadata
    name: social-media
    files: 
      - label: Social media image and description
        file: "data/social.yaml"
        preview_path: /
        extension: "yaml"
        create: false
        name: socialitems
        fields:
          - {label: "Social media description", name: "social_description", widget: string}
          - {label: Social media image, name: social_image, widget: image, hint: 'Optimum resolution is 1200x675 pixels'}
          